---
title: "data"
output: github_document
date: "2022-12-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(readxl)
library(corrplot)
library(performance)
library(car)
library(interactions)
library(caret)
library(MASS)
```


```{r import data}
body_df=read_excel("data/body_density_data.xlsx") %>%
  janitor::clean_names() %>%
  dplyr::select(-bodyfat_brozek,-body_density,-id)
```

```{r descriptive stat}
# all are continuous data

sum = function(variable){
  tibble(
    mean = mean(variable),
    sd = sd(variable),
    median = median(variable),
    maximum = max(variable),
    minimum = min(variable),
    IQR = IQR(variable)
  )
}

table=map(body_df, sum) %>% 
  bind_rows() %>% 
  mutate(variable = names(body_df)) %>% 
  dplyr::select(variable,everything()) %>% 
  filter(variable!="id") %>%
  knitr::kable(digits = 2, 
               caption = "Descriptive statistics of continuous variables") 

table
```


```{r  check outcome variable}
boxplot(body_df$bodyfat_siri,main='Percent body fat using Siri’s equation')

```

```{r}
body_df %>% dplyr::select(-bodyfat_siri)%>%
  funModeling::plot_num()
```

```{r}
  body_df=body_df %>%
  mutate(i_weight = 1/weight,
         i_neck = 1/neck,
         i_chest = 1/chest,
         i_abdomen = 1/abdomen,
         i_hip = 1/hip,
         i_thigh = 1/thigh,
         i_knee = 1/knee,
         i_ankle = 1/ankle,
         i_bicep = 1/bicep) %>%
  dplyr::select(-weight, -neck, -chest, -abdomen,
         -hip, -thigh, -knee, -ankle, -bicep)
```

```{r}
body_df %>%
  funModeling::plot_num()


```

```{r correlation}
# check multicollinearity
cor_df=
  body_df %>%
  cor() ## Correlation coefficient
corrplot(cor(cor_df), type = "upper", diag = FALSE)

```

```{r}

#Raw VIF
mult.fit <- lm(bodyfat_siri ~ .,data = body_df)
summary(mult.fit)
vif_val <- vif(mult.fit)
name <- str_to_title (names(vif_val))
vifdf <- 
  tibble(variable = name, vif = vif_val) %>%
  mutate(variable = fct_reorder(variable,vif_val))
ggplot(data = vifdf,aes(y = variable, x = vif_val)) +
  geom_col() +
  geom_vline(xintercept = 5,colour="red",linetype = "longdash") +
 theme_bw()

```


```{r}
bf_data=body_df %>%
dplyr::select(-i_weight,-i_hip,-i_chest,-i_thigh) 
write_csv(bf_data,"data/bf_data.csv")
mult.fit2 <- lm(bodyfat_siri ~ .,data = bf_data)
vif_val <- vif(mult.fit2)
name <- str_to_title (names(vif_val))
vifdf <- 
  tibble(variable = name, vif = vif_val) %>%
  mutate(variable = fct_reorder(variable,vif_val))
ggplot(data = vifdf,aes(y = variable, x = vif_val)) +
  geom_col() +
  geom_vline(xintercept = 5,colour="red",linetype = "longdash") +
 theme_bw()
```


```{r}
bf_data = read_csv("./data/bf_data.csv") 
bf_predictors = bf_data %>% 
  select(-bodyfat_siri) %>% 
  mutate(age = as.numeric(age),
         height = as.numeric(height),
         neck = as.numeric(neck),
         abdomen = as.numeric(abdomen),
         knee = as.numeric(knee),
         ankle = as.numeric(ankle),
         bicep = as.numeric(bicep),
         forearm = as.numeric(forearm),
         wrist = as.numeric(wrist),
         )

s.t_age <- shapiro.test(bf_predictors$age) 
s.t_height <- shapiro.test(bf_predictors$height) 
s.t_neck <- shapiro.test(bf_predictors$neck) 
s.t_abdomen <- shapiro.test(bf_predictors$abdomen) 
s.t_knee <- shapiro.test(bf_predictors$knee) 
s.t_ankle <- shapiro.test(bf_predictors$ankle) 
s.t_bicep <- shapiro.test(bf_predictors$bicep) 
s.t_forearm <- shapiro.test(bf_predictors$forearm) 
s.t_wrist <- shapiro.test(bf_predictors$wrist) 

rbind(s.t_age, s.t_height, s.t_neck, s.t_abdomen, s.t_knee, s.t_ankle, s.t_bicep, s.t_forearm, s.t_wrist) 
```

```{r}
h_trans = bf_predictors %>% 
  select(2) %>%
  exp()
hist(h_trans[,1], main = paste("Hist. of", "height", sep = " "), xlab = "height")
shapiro.test(h_trans$height) 
```

```{r}
step.fit = lm(bodyfat_siri ~ ., data = bf_data)
step(step.fit, direction = "both")
```

```{r}
fit1 = lm(bodyfat_siri ~ age + height + neck + abdomen + forearm + 
    wrist, data = bf_data)
par(mfrow = c(2,2))
plot(fit1)
```

```{r}

inter2=update(fit1, .~.+forearm*height)
interact_plot(inter2,pred = forearm, modx = height) 

inter3=update(fit1, .~.+neck*height)
interact_plot(inter3,pred = neck, modx = height) 

inter4=update(fit1, .~.+wrist*age)
interact_plot(inter4,pred = wrist, modx = age) 

anova(fit1,inter2)
anova(fit1,inter3)

anova(fit1,inter4)


```

```{r cv}

model13 = train(bodyfat_siri ~ age + height + neck + abdomen + forearm + wrist + height*neck ,
                   data = bf_data,
                   trControl = train,
                   method = 'lm',
                   na.action = na.pass)
model13$finalModel
print(model13)

model14 = train(bodyfat_siri ~ age + height + neck + abdomen + forearm + wrist + wrist*age ,
                   data = bf_data,
                   trControl = train,
                   method = 'lm',
                   na.action = na.pass)
model14$finalModel
print(model14)

```

```{r}
fit_adj4 = lm(formula = bodyfat_siri ~ age + height + neck + abdomen + forearm + wrist + height*neck, data = bf_data)
summary(fit_adj4)
plot(fit_adj4)

plot(fit_adj4, which = 4)

surgOut = bf_data[-c(39,192,250),]
fit_adj4_without=lm(formula = bodyfat_siri ~ age + height + neck + abdomen + forearm + wrist + height*neck,data=surgOut)
par(mfrow = c(2,2))
plot(fit_adj4_without)
summary(fit_adj4_without)

bf_data_adj= bf_data %>%
  dplyr::select(-knee,-bicep,-ankle) %>%
  mutate(height_neck=height*neck)

glmnet(as.matrix(bf_data[2:6]), bf_data$, lambda = 1, alpha = 0)%>%
  coef()
```